### ISSUE TITLE
需要配置deviceName

### ISSUE THREAD

**Issue by KUTEJiang** [JTiger0431/DingdongHelper#2]
使用APPium最新版本时运行报错：
selenium.common.exceptions.SessionNotCreatedException: Message: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'deviceName' can't be blank

需要在最开始的init配置中加上deviceName,deviceName通过adb devices查询

**Comment by JTiger0431** [comment]
多谢提醒，我在 commit 之前隐掉了，我把这个字段加回来
